=== CO18344/XML/assignment/order.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:orders="http://www.assignment.com/orders"
targetNamespace="http://www.assignment.com/orders"
elementFormDefault="qualified">
<element name="orders">
	<complexType>
		<sequence>
			<element name="order" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="description" type="string"/>
						<element name="lineItems">
							<complexType>
								<sequence>
									<element name="lineItem" minOccurs="0" maxOccurs="unbounded">
										<complexType>
											<sequence>
												<element name="book" type="orders:BookType"/>
												<element name="qty" type="nonNegativeInteger"/>
												<element name="price" type="positiveInteger"/>
											</sequence>
										</complexType>
									</element>
								</sequence>
							</complexType>
						</element>
					</sequence>
					<attributeGroup ref="orders:OrderAttributes"/>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>

<attributeGroup name="OrderAttributes">
	<attribute name="orderID" type="positiveInteger"/>
	<attribute name="requestDate" type="date"/>
</attributeGroup>



<complexType name="BookType">
		<sequence>
			<element name="bookName" type="string"/>
			<element name="genre">
					<simpleType>
						<restriction base="string">
							<enumeration value="science-fiction"/>
							<enumeration value="mystery"/>
							<enumeration value="thriller"/>
							<enumeration value="drama"/>
						</restriction>
					</simpleType>
			</element>
			<element name="publishDate" type="date"/>
			<element name="authors">
				<complexType>
					<sequence>
						<element name="author">
							<complexType>
								<sequence>
									<element name="bio" type="string"/>
									<element name="lastname" type="string"/>
									<element name="firstname" type="string"/>
									<element name="penName" type="string" minOccurs="0" maxOccurs="1"/>
								</sequence>
							</complexType>
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
		<attribute name="bookID" type="positiveInteger"/>
</complexType>


</schema>

=== CO18344/XML/assignment/order.xml
<?xml version="1.0"?>
<orders xmlns="http://www.assignment.com/orders"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.assignment.com/orders order.xsd">

<order orderID="1" requestDate="2020-05-23">
	<description>The order belongs to CCET</description>
	<lineItems>
		<lineItem>
			<book bookID="21">
				<bookName>Harry Potter</bookName>
				<genre>science-fiction</genre>
				<publishDate>2020-05-23</publishDate>
				<authors>
					<author>
						<bio>Biodata</bio>
						<lastname>Singh</lastname>
						<firstname>Satvik</firstname>
						<penName>This is my pen name</penName>
					</author>
				</authors>
			</book>
			<qty>5</qty>
			<price>156</price>
		</lineItem>
		<lineItem>
			<book bookID="24">
				<bookName>Harry Potter2</bookName>
				<genre>science-fiction</genre>
				<publishDate>2020-05-23</publishDate>
				<authors>
					<author>
						<bio>Biodata2</bio>
						<lastname>Singh2</lastname>
						<firstname>Satvik2</firstname>
						<penName>This is my pen name2</penName>
					</author>
				</authors>
			</book>
			<qty>6</qty>
			<price>151</price>
		</lineItem>
	</lineItems>

</order>
</orders>
